// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/9/2026, 2:47:49 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/franccescobuscicchio/Desktop/rituali-creativi-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/franccescobuscicchio/Desktop/rituali-creativi-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/franccescobuscicchio/Desktop/rituali-creativi-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/franccescobuscicchio/Desktop/rituali-creativi-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/franccescobuscicchio/Desktop/rituali-creativi-nuxt/plugins/**/*.{js,ts,mjs}","/Users/franccescobuscicchio/Desktop/rituali-creativi-nuxt/composables/**/*.{js,ts,mjs}","/Users/franccescobuscicchio/Desktop/rituali-creativi-nuxt/utils/**/*.{js,ts,mjs}","/Users/franccescobuscicchio/Desktop/rituali-creativi-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/franccescobuscicchio/Desktop/rituali-creativi-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/franccescobuscicchio/Desktop/rituali-creativi-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/franccescobuscicchio/Desktop/rituali-creativi-nuxt/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;